const SAVE_KEY="station-here-save-v2",W=23,H=17,VW=11,VH=9;
const $=s=>document.querySelector(s),rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)];
const phases=["Утро","День","Вечер","Ночь"];
const tools={hand:["✋","Рука","универсальное действие"],seed:["🌱","Семена","посадить на грядке"],water:["💧","Лейка","полить грядку"],hammer:["🔨","Молоток","чинить здания"],crowbar:["⛏","Лом","разбирать и искать ресурсы"],radio:["📻","Радио","слушать эфир"]};
const toolOrder=["hand","seed","water","hammer","crowbar","radio"];
const tiles={grass:["","Заросший двор","grass"],dirt:["","Грунтовая тропа","dirt"],snow:["","Серый снег","snow"],pine:["♠","Сосны","pine"],rail:["═","Пути","rail"],platform:["▣","Платформа","platform"],home:["⌂","Дом обходчика","home"],garden:["◌","Грядка","garden"],greenhouse:["♧","Тепличный вагон","greenhouse"],workshop:["⚒","Мастерская","workshop"],well:["◍","Водокачка","well"],depot:["▤","Депо","depot"],dorm:["▥","Общежитие","dorm"],radio:["◉","Сигнальная башня","radio"],storage:["▦","Склад","storage"],grave:["†","Кладбище шпал","grave"],gate:["⇆","Выезд на дрезине","gate"],pond:["≈","Заледеневшая канава","pond"]};
const solid=new Set(["pine","pond"]),gardens=[[5,7],[6,7],[7,7],[8,7],[5,8],[6,8],[7,8],[8,8],[5,9],[6,9],[7,9],[8,9]];
const npcStart=[{id:"marfa",name:"Марфа",role:"дежурная",heart:1,mood:"смотрит на пустое расписание",x:10,y:6},{id:"egor",name:"Егор",role:"механик",heart:1,mood:"слушает дрезину",x:7,y:12},{id:"lida",name:"Лида",role:"медсестра",heart:1,mood:"кипятит воду",x:13,y:13}];
const routes=[
 {name:"Станция Сухая",fuel:2,mem:"На Сухой слухи ценнее патронов.",txt:"На Сухой торгуют солью, сухарями и новостями.",reward:()=>({food:rnd(1,3),metal:rnd(1,2),seeds:1})},
 {name:"Дом у насыпи",fuel:3,mem:"Домовой боится предметов, которые держат дом на месте.",txt:"В подъезде пахнет сырой штукатуркой. На стене детский рисунок станции.",reward:()=>({wood:rnd(2,4),meds:Math.random()<.5?1:0})},
 {name:"Старый блокпост",fuel:4,mem:"Срочники реагируют на правильно оформленный приказ.",txt:"Молчащие Срочники провожают дрезину пустыми лицами.",reward:()=>({metal:rnd(2,5),ammo:rnd(0,2)})}
];
let walkTimer=null,state=migrate(load())||fresh();
function fresh(){return{day:1,phaseIndex:0,stamina:8,hope:42,threat:8,selectedTool:"hand",player:{x:11,y:8,facing:"down",walking:false,step:0},resources:{food:8,water:6,fuel:6,metal:5,wood:4,meds:2,seeds:5,crop:0,ammo:2},buildings:{greenhouse:0,workshop:0,well:0,depot:0,dorm:0,radio:0},plots:gardens.map(()=>({crop:false,stage:0,watered:false})),npcs:npcStart.map(n=>({...n})),memory:["Станция Здесь — то, что ты строишь. Станция Нигде — то, что зовёт."],flags:{firstRadio:false,visitor:false},log:[]}}
function migrate(s){if(!s)return null;if(!s.selectedTool)s.selectedTool="hand";if(!s.player)s.player={x:11,y:8};if(!s.player.facing)s.player.facing="down";if(typeof s.player.walking!=="boolean")s.player.walking=false;if(!s.resources.crop&&s.resources.crop!==0)s.resources.crop=0;if(!s.npcs||!s.npcs.length)s.npcs=npcStart.map(n=>({...n}));return s}
function load(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))}catch{return null}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function map(){let m=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1||x===1&&y<6||x===W-2&&y>9||x===2&&y===2||x===19&&y===3||x===20&&y===12?"pine":x>=17&&y>=2&&y<=5?"snow":"grass"));for(let x=1;x<W-1;x++)m[8][x]="rail";for(let y=3;y<15;y++)m[y][11]="dirt";for(let x=4;x<=15;x++)m[11][x]="dirt";for(let x=4;x<=8;x++)m[6][x]="dirt";for(let x=13;x<=18;x++)m[6][x]="dirt";Object.entries({"11,8":"platform","11,13":"home","6,4":"greenhouse","6,12":"workshop","16,4":"well","16,12":"depot","11,2":"radio","13,14":"dorm","4,13":"storage","18,3":"grave","21,8":"gate","19,5":"pond","19,6":"pond"}).forEach(([k,v])=>{let[x,y]=k.split(',').map(Number);m[y][x]=v});gardens.forEach(([x,y])=>m[y][x]="garden");return m}
function phase(){return phases[state.phaseIndex]}
function addLog(t,imp=false){state.log.unshift({text:t,important:imp});state.log=state.log.slice(0,80);save()}
function remember(t){if(!state.memory.includes(t)){state.memory.unshift(t);state.memory=state.memory.slice(0,14);addLog("Память станции: "+t,true)}}
function tile(){return map()[state.player.y][state.player.x]}
function npcAt(x,y){return state.npcs.find(n=>n.x===x&&n.y===y)}
function setTool(tool){if(!tools[tool])return;state.selectedTool=tool;save();renderToolbelt();context()}
function move(dx,dy){let p=state.player,nx=p.x+dx,ny=p.y+dy;if(dx)p.facing=dx>0?"right":"left";if(dy)p.facing=dy>0?"down":"up";if(nx<0||ny<0||nx>=W||ny>=H)return;let t=map()[ny][nx];if(solid.has(t)){addLog(tiles[t][1]+": дальше не пройти.");return render()}p.x=nx;p.y=ny;p.walking=true;p.step=(p.step||0)+1;clearTimeout(walkTimer);save();render();walkTimer=setTimeout(()=>{state.player.walking=false;renderMap()},170)}
function clickTile(x,y){let d=Math.abs(x-state.player.x)+Math.abs(y-state.player.y);if(d===0)return interact();if(d===1)return move(x-state.player.x,y-state.player.y);addLog("Слишком далеко. Подойди ближе.")}
function interact(){let n=npcAt(state.player.x,state.player.y);if(n&&state.selectedTool==="hand")return talk(n);let t=tile();if(state.selectedTool==="hand")return universal(t);if(state.selectedTool==="seed")return t==="garden"?plantGarden():addLog("Семена можно посадить только на грядке.");if(state.selectedTool==="water")return t==="garden"?waterGarden():addLog("Лейка нужна на грядке. Здесь вода просто уйдёт в грязь.");if(state.selectedTool==="hammer")return canRepair(t)?repair(t):addLog("Молотком здесь нечего чинить.");if(state.selectedTool==="crowbar")return crowbar(t);if(state.selectedTool==="radio")return t==="radio"?radio():addLog("Эфир слабый. У башни сигнал будет чище.")}
function universal(t){return({garden:gardenAction,greenhouse:()=>repair("greenhouse"),workshop:()=>repair("workshop"),well,dorm,radio,storage,grave,gate,home,platform,rail,dirt:yard,grass:yard,snow:yard}[t]||yard)()}
function canRepair(t){return["greenhouse","workshop","well","depot","dorm","radio"].includes(t)}
function crowbar(t){if(t==="storage")return storage();if(["grass","dirt","snow"].includes(t))return yard();if(t==="rail")return rail();addLog("Лом скользит по поверхности. Толку мало.")}
function time(txt,cost=1){state.stamina=clamp(state.stamina-cost,0,10);if(txt)addLog(txt);if(state.stamina<=0&&state.phaseIndex<3){addLog("Сил больше нет. День сминается в серый вечер.",true);state.phaseIndex=3}else state.phaseIndex++;if(state.phaseIndex>=4)night();save();render()}
function night(){let eat=Math.max(1,state.npcs.length);state.resources.food-=eat;state.resources.water-=eat;state.threat+=rnd(2,5);state.plots.forEach(p=>{if(p.crop&&p.watered)p.stage=clamp(p.stage+1,0,3);if(p.crop&&!p.watered&&Math.random()<.35)p.crop=false;p.watered=false});if(state.resources.food<0||state.resources.water<0){state.hope-=10;state.resources.food=Math.max(0,state.resources.food);state.resources.water=Math.max(0,state.resources.water);addLog("Ночью не хватило еды или воды. Утром люди говорят тише.",true)}pick(state.threat>55?[watcher,domovoy,soldiers]:[radioNight,watcher,domovoy,quiet,visitor])();state.day++;state.phaseIndex=0;state.stamina=8+Math.min(2,state.buildings.dorm);state.hope=clamp(state.hope,0,100);state.threat=clamp(state.threat,0,100);if(state.day===6)addLog("Пятые сутки пережиты. Станция уже не выглядит случайной остановкой.",true)}
function radioNight(){state.hope-=2;state.threat+=4;addLog("Ночью радио включается само: “Здесь — временно. Нигде — навсегда.”",true);remember("Радио не любит, когда станция становится домом.")}
function watcher(){if(state.buildings.workshop||state.buildings.depot){state.threat-=8;addLog("Путевой Смотритель проходит мимо. Отремонтированные стрелки успокаивают его.",true)}else{state.resources.metal=Math.max(0,state.resources.metal-1);state.hope-=6;addLog("Смотритель всю ночь стучит ключом по рельсам. Утром часть металла исчезает.",true)}}
function domovoy(){if(state.buildings.dorm||state.memory.some(m=>m.includes("Домовой"))){state.hope+=2;addLog("Домовой шуршит в общежитии, но сегодня не вредничает.",true)}else{state.hope-=7;state.resources.wood=Math.max(0,state.resources.wood-1);addLog("Комнаты меняются местами. Лида клянётся, что спала в другом вагоне.",true);remember("Домовой боится станций, где у каждого есть своё место.")}}
function soldiers(){if(state.resources.ammo>0)state.resources.ammo--;state.hope-=8;state.threat-=12;addLog("Молчащие Срочники требуют документы на станцию. Марфа ставит печать на пустой бумаге.",true);remember("Приказ иногда сильнее смерти, если произнести его уверенно.")}
function quiet(){state.hope+=4;state.threat-=3;addLog("Ночь проходит тихо. Только тепличный вагон потрескивает от холода.")}
function visitor(){if(!state.flags.visitor&&state.day>2){state.flags.visitor=true;state.hope+=7;state.resources.seeds+=2;addLog("Под утро приходит мальчишка с мешком семян. Он говорит, что уже жил здесь.",true);remember("Некоторые жители приходят раньше своих имён.")}else quiet()}
function gardenAction(){let p=plot();if(!p)return;if(!p.crop)return plantGarden();if(p.stage>=3)return harvestGarden();if(!p.watered)return waterGarden();addLog("Эта грядка уже полита.")}
function plot(){return state.plots[gardenIndex(state.player.x,state.player.y)]}
function plantGarden(){let p=plot();if(!p)return;if(p.crop)return addLog("Здесь уже растёт урожай.");if(state.resources.seeds<=0)return addLog("Семян нет.");state.resources.seeds--;p.crop=true;p.stage=0;p.watered=false;return time("Ты сажаешь семена в мерзловатую землю между шпалами.")}
function waterGarden(){let p=plot();if(!p||!p.crop)return addLog("Сначала нужно посадить семена.");if(p.watered)return addLog("Эта грядка уже полита.");if(state.resources.water<=0)return addLog("Воды нет.");state.resources.water--;p.watered=true;return time("Ты поливаешь грядку.")}
function harvestGarden(){let p=plot();if(!p||!p.crop||p.stage<3)return addLog("Собирать пока нечего.");let a=2+state.buildings.greenhouse;state.resources.crop+=a;state.resources.food+=Math.floor(a/2);p.crop=false;p.stage=0;return time("Урожай собран: +"+a+" овощей.")}
function gardenIndex(x,y){return gardens.findIndex(([gx,gy])=>gx===x&&gy===y)}
function repair(id){let nm={greenhouse:"тепличный вагон",workshop:"мастерскую",depot:"депо",dorm:"общежитие",radio:"сигнальную башню",well:"водокачку"}[id],lvl=state.buildings[id]||0;if(lvl>=2)return addLog("Здесь пока больше нечего чинить.");let mc=2+lvl,wc=1+lvl;if(state.resources.metal<mc||state.resources.wood<wc)return addLog("Для ремонта нужны металл x"+mc+" и дерево x"+wc+".");state.resources.metal-=mc;state.resources.wood-=wc;state.buildings[id]=lvl+1;state.hope+=5;time("Ты ремонтируешь "+nm+". Станция становится чуть меньше похожа на труп.",2)}
function well(){if(state.buildings.well<2&&state.resources.metal>=2&&state.resources.wood>=1&&Math.random()<.35)return repair("well");let a=2+state.buildings.well*2;state.resources.water+=a;time("Водокачка кашляет ржавчиной, но даёт воду: +"+a+".")}
function dorm(){if(!state.buildings.dorm&&state.resources.metal>=2&&state.resources.wood>=1)return repair("dorm");talk(pick(state.npcs))}
function talk(n){n.heart=clamp(n.heart+1,0,5);state.hope+=3;let l={marfa:"Марфа говорит, что расписание нужно вести даже после конца света.",egor:"Егор признаётся, что слышит двигатель дрезины во сне.",lida:"Лида просит не называть больных безнадёжными."};time(l[n.id]||"Вы говорите у печки.")}
function radio(){if(!state.flags.firstRadio){state.flags.firstRadio=true;remember("Станция Нигде знает настоящее имя обходчика.");return time("Ты включаешь радио. Вместо эфира — дыхание и фраза: “Не строй Здесь слишком крепко.”")}if(state.buildings.radio<2&&state.resources.metal>=2&&Math.random()<.45)return repair("radio");let text=pick([()=>{state.resources.fuel++;return"В эфире называют старый склад ГСМ: +1 топливо."},()=>{state.resources.seeds++;return"Под башней находишь пакет семян."},()=>{state.threat+=6;remember("Чем чаще слушаешь Нигде, тем легче Нигде слышит тебя.");return"Радио зовёт слишком ясно. Станция становится холоднее."}])();time(text)}
function storage(){let f=pick(["metal","wood","food","seeds"]),a=f==="food"?2:1;state.resources[f]+=a;state.threat++;time("Ты разбираешь склад и находишь: "+rname(f)+" +"+a+".")}
function grave(){state.hope+=2;remember(pick(["Мёртвые станции ждут, пока кто-нибудь снова назовёт их домом.","Кладбище шпал помнит маршруты лучше карты.","Иногда память — предупреждение из будущего."]));time("Ты поправляешь таблички на кладбище шпал.")}
function gate(){if(phase()==="Ночь")return addLog("Ночью на дрезине не выезжают.");let r=routes[(state.day+state.phaseIndex)%routes.length];if(state.resources.fuel<r.fuel)return addLog("До маршрута “"+r.name+"” нужно топливо x"+r.fuel+".");state.resources.fuel-=r.fuel;let rew=r.reward();Object.entries(rew).forEach(([k,v])=>state.resources[k]+=v);state.threat+=rnd(3,9);remember(r.mem);time(r.txt+" Добыча: "+Object.entries(rew).filter(([,v])=>v>0).map(([k,v])=>rname(k)+" +"+v).join(", ")+".",2)}
function home(){state.stamina=clamp(state.stamina+2,0,10);state.hope++;time("Ты чинишь печку, кипятишь воду и переписываешь список дел.",0)}
function platform(){state.hope+=3;state.threat=Math.max(0,state.threat-2);time("Ты чистишь платформу и вешаешь табличку: “Станция Здесь”.")}
function rail(){state.threat=Math.max(0,state.threat-1);time("Ты проверяешь путь. Рельсы холодные. Это хороший знак.")}
function yard(){let w=Math.random()<.6;if(w)state.resources.wood++;else state.resources.metal++;time(w?"Во дворе находишь сухую доску.":"В снегу торчит кусок годного металла.")}
function rname(k){return{food:"еда",water:"вода",fuel:"топливо",metal:"металл",wood:"дерево",meds:"лекарства",seeds:"семена",crop:"овощи",ammo:"патроны"}[k]||k}
function cam(){let sx=clamp(state.player.x-Math.floor(VW/2),0,W-VW),sy=clamp(state.player.y-Math.floor(VH/2),0,H-VH);return{sx,sy}}
function render(){stats();renderMap();buildings();npcs();memory();log();context();renderToolbelt()}
function stats(){$("#day").textContent=state.day;$("#phase").textContent=phase();$("#stamina").textContent=state.stamina;$("#hope").textContent=state.hope;$("#threat").textContent=state.threat;document.body.classList.remove("phase-morning","phase-day","phase-evening","phase-night");document.body.classList.add(["phase-morning","phase-day","phase-evening","phase-night"][state.phaseIndex]||"phase-morning");Object.entries(state.resources).forEach(([k,v])=>{let e=$("#res-"+k);if(e)e.textContent=v})}
function renderMap(){let b=$("#station-map"),m=map(),{sx,sy}=cam();b.style.setProperty("--view-w",VW);b.innerHTML="";for(let y=sy;y<sy+VH;y++)for(let x=sx;x<sx+VW;x++){let t=m[y][x],inf=tiles[t],n=npcAt(x,y),c=document.createElement("button");c.type="button";c.className="station-cell "+inf[2];c.title=n?n.name+" — "+n.role:inf[1];let obj=n?({marfa:"М",egor:"Е",lida:"Л"}[n.id]||"?"):tileObject(t,x,y);c.innerHTML=`<span class="tile-art">${obj}</span><small>${short(t,x,y)}</small>`;if(state.player.x===x&&state.player.y===y){c.classList.add("player");c.innerHTML+=`<span class="hero-sprite ${state.player.facing} ${state.player.walking?"walk":""}"></span>`}c.onclick=()=>clickTile(x,y);b.appendChild(c)}let label=$("#camera-label");if(label)label.innerHTML=`камера: <b>${sx+1}:${sy+1}</b> / мир ${W}×${H}`}
function tileObject(t,x,y){if(t==="garden"){let p=state.plots[gardenIndex(x,y)];if(!p||!p.crop)return"";return p.stage>=3?"✿":"♧"}return tiles[t][0]}
function short(t,x,y){let n=npcAt(x,y);if(n)return n.name;if(t==="garden"){let p=state.plots[gardenIndex(x,y)];if(!p||!p.crop)return"грядка";return p.stage>=3?"урожай":"рост "+p.stage}return{platform:"центр",home:"дом",greenhouse:"теплица",workshop:"цех",well:"вода",depot:"депо",dorm:"жители",radio:"радио",storage:"склад",grave:"память",gate:"выезд",rail:"путь",dirt:"тропа",grass:"трава",snow:"снег",pine:"лес",pond:"лёд"}[t]||""}
function buildings(){let box=$("#buildings"),names={greenhouse:"Тепличный вагон",workshop:"Мастерская",well:"Водокачка",depot:"Депо",dorm:"Общежитие",radio:"Сигнальная башня"};box.innerHTML="";Object.entries(names).forEach(([k,n])=>{let d=document.createElement("div");d.className="upgrade";d.innerHTML=`<span>${n}</span><b>${"▰".repeat(state.buildings[k])}${"▱".repeat(2-state.buildings[k])}</b>`;box.appendChild(d)})}
function npcs(){let box=$("#npcs");box.innerHTML="";state.npcs.forEach(n=>{let d=document.createElement("div");d.className="npc-card";d.innerHTML=`<b>${n.name}</b><span>${n.role}</span><small>${"♥".repeat(n.heart)}${"♡".repeat(5-n.heart)} · ${n.mood}</small>`;box.appendChild(d)})}
function memory(){let box=$("#memory-list");box.innerHTML="";state.memory.forEach(t=>{let d=document.createElement("div");d.className="memory-item";d.textContent=t;box.appendChild(d)})}
function log(){let box=$("#log");box.innerHTML="";state.log.forEach(e=>{let p=document.createElement("p");p.className=e.important?"important":"";p.textContent=e.text;box.appendChild(p)})}
function renderToolbelt(){document.querySelectorAll("[data-tool]").forEach(btn=>btn.classList.toggle("active",btn.dataset.tool===state.selectedTool));let el=$("#current-tool"),t=tools[state.selectedTool];if(el&&t)el.textContent=`${t[0]} ${t[1]}: ${t[2]}`}
function context(){let n=npcAt(state.player.x,state.player.y);if(n){$("#place-name").textContent=n.name;$("#place-desc").textContent=n.role+". "+n.mood+". Выбери руку и поговори с ним.";$("#main-action").textContent="Поговорить";return}let t=tile(),tool=state.selectedTool;$("#place-name").textContent=tiles[t][1];$("#place-desc").textContent={garden:"Посади, полей или собери урожай.",greenhouse:"Тепличный вагон повышает урожай после ремонта.",workshop:"Мастерская помогает чинить путь и отпугивать Смотрителя.",well:"Водокачка даёт воду.",depot:"Депо хранит дрезину.",dorm:"Общежитие для жителей.",radio:"Башня ловит Нигде и чужие частоты.",storage:"Склад можно разобрать ради ресурсов.",grave:"Кладбище шпал отдаёт память.",gate:"Выезд на дрезине.",home:"Дом обходчика. Тут можно восстановить силы.",platform:"Сердце станции.",rail:"Пути надо проверять.",grass:"Заросший двор станции.",dirt:"Тропа между вагонами.",snow:"Серый снег у края станции."}[t]||"";$("#main-action").textContent=(tools[tool]?.[0]||"")+" Использовать"}
function openMemory(){$("#memoryDrawer").classList.remove("hidden");memory()}function closeMemory(){$("#memoryDrawer").classList.add("hidden")}function openHelp(){$("#helpDrawer").classList.remove("hidden")}function closeHelp(){$("#helpDrawer").classList.add("hidden")}
function bind(){$("#main-action").onclick=interact;$("#restBtn").onclick=home;$("#memoryBtn").onclick=openMemory;$("#newRunBtn").onclick=()=>{localStorage.removeItem(SAVE_KEY);state=fresh();state.log=[];addLog("Ты возвращаешься на пустую платформу. На табличке мелом написано: “Здесь”.",true);render()};$("#closeMemoryBtn").onclick=closeMemory;$("#helpBtn").onclick=openHelp;$("#closeHelpBtn").onclick=closeHelp;document.querySelectorAll("[data-tool]").forEach(btn=>btn.onclick=()=>setTool(btn.dataset.tool));window.addEventListener("keydown",e=>{let k=e.key.toLowerCase(),mv={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();if(mv[k])move(...mv[k]);if(e.key===" "||e.key==="Enter")interact();if(k>="1"&&k<="6")setTool(toolOrder[Number(k)-1]);if(k==="r")home();if(k==="m")openMemory();if(k==="n")$("#newRunBtn").click()})}
if(!state.log.length){addLog("Ты ставишь на платформе табличку: “Станция Здесь”. Вдалеке радио шепчет: “Нигде”.",true);addLog("Теперь это 2D-карта: камера следует за тобой, а не показывает всю станцию сразу.")}
bind();render();
