const SAVE_KEY="station-here-save-v3",W=23,H=17,VW=11,VH=9;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)];
const phases=["Утро","День","Вечер","Ночь"],seasons=["Оттепель","Сухой холод","Поздняя весна","Глухая осень"];
const weatherList=[["ясно","Солнце режет снег, но люди говорят громче."],["туман","Звуки приходят раньше предметов."],["снег","Пути заносит, зато следы видны лучше."],["дождь","Крыши текут, но грядки пьют сами."],["радиошторм","Эфир шевелится даже в выключенных приёмниках."]];
const tools={hand:["✋","Рука","универсальное действие"],seed:["🌱","Семена","посадить на грядке"],water:["💧","Лейка","полить грядку"],hammer:["🔨","Молоток","чинить здания"],crowbar:["⛏","Лом","разбирать и искать ресурсы"],radio:["📻","Радио","слушать эфир"]},toolOrder=["hand","seed","water","hammer","crowbar","radio"];
const tiles={grass:["","Заросший двор","grass"],dirt:["","Грунтовая тропа","dirt"],snow:["","Серый снег","snow"],pine:["♠","Сосны","pine"],rail:["═","Пути","rail"],platform:["▣","Платформа","platform"],home:["⌂","Дом обходчика","home"],garden:["◌","Грядка","garden"],greenhouse:["♧","Тепличный вагон","greenhouse"],workshop:["⚒","Мастерская","workshop"],well:["◍","Водокачка","well"],depot:["▤","Депо","depot"],dorm:["▥","Общежитие","dorm"],radio:["◉","Сигнальная башня","radio"],storage:["▦","Склад","storage"],grave:["†","Кладбище шпал","grave"],gate:["⇆","Выезд на дрезине","gate"],pond:["≈","Заледеневшая канава","pond"]};
const solid=new Set(["pine","pond"]),gardens=[[5,7],[6,7],[7,7],[8,7],[5,8],[6,8],[7,8],[8,8],[5,9],[6,9],[7,9],[8,9]];
const npcStart=[
 {id:"marfa",name:"Марфа",role:"дежурная",heart:1,mood:"смотрит на пустое расписание",x:10,y:6,portrait:"М",color:"#e0ad47",want:"еда и вода в кладовой"},
 {id:"egor",name:"Егор",role:"механик",heart:1,mood:"слушает дрезину",x:7,y:12,portrait:"Е",color:"#71d6ff",want:"мастерская и ремонтные наборы"},
 {id:"lida",name:"Лида",role:"медсестра",heart:1,mood:"кипятит воду",x:13,y:13,portrait:"Л",color:"#ffb2df",want:"лекарства и чистая вода"}
];
const routes=[
 {id:"sukhaya",name:"Станция Сухая",fuel:2,risk:"низкий",mem:"На Сухой слухи ценнее патронов.",txt:"На Сухой торгуют солью, сухарями и новостями.",reward:()=>({food:rnd(2,4),metal:rnd(1,2),seeds:1,document:Math.random()<.35?1:0})},
 {id:"embankment",name:"Дом у насыпи",fuel:3,risk:"средний",mem:"Домовой боится предметов, которые держат дом на месте.",txt:"В подъезде пахнет сырой штукатуркой. На стене детский рисунок станции.",reward:()=>({wood:rnd(3,5),meds:Math.random()<.55?1:0,relic:Math.random()<.25?1:0})},
 {id:"checkpoint",name:"Старый блокпост",fuel:4,risk:"опасный",mem:"Срочники реагируют на правильно оформленный приказ.",txt:"Молчащие Срочники провожают дрезину пустыми лицами.",reward:()=>({metal:rnd(3,6),ammo:rnd(0,2),document:1})},
 {id:"tunnel",name:"Тоннель без длины",fuel:5,risk:"аномальный",mem:"Тоннель возвращает не тех, кто вошёл, а тех, кто нужен станции.",txt:"В тоннеле дрезина едет дольше, чем должен существовать этот перегон.",reward:()=>({battery:1,relic:1,fuel:Math.random()<.5?1:0})}
];
const recipes=[
 {id:"repairKit",name:"Ремонтный набор",icon:"🧰",cost:{metal:2,wood:1},out:{repairKit:1},desc:"Ускоряет ремонт и может заменить часть материалов."},
 {id:"filter",name:"Водяной фильтр",icon:"🧪",cost:{metal:1,wood:1},out:{filter:1},desc:"Можно использовать у водокачки: +4 воды."},
 {id:"fuelCan",name:"Самодельное топливо",icon:"⛽",cost:{crop:2,metal:1},out:{fuel:2},desc:"Горит плохо, но дрезина едет."},
 {id:"medkit",name:"Аптечка",icon:"💊",cost:{meds:1,water:1},out:{medkit:1},desc:"Восстанавливает силы и надежду."},
 {id:"tea",name:"Чай из тепличных трав",icon:"🍵",cost:{crop:1,water:1},out:{tea:1},desc:"Маленький уют против большого конца света."},
 {id:"flare",name:"Сигнальный факел",icon:"🔥",cost:{wood:1,ammo:1},out:{flare:1},desc:"Снижает угрозу ночью."}
];
const quests=[
 {id:"marfa_stock",npc:"Марфа",title:"Запас на случай тишины",desc:"Держи на станции еду x12 и воду x10.",need:s=>s.resources.food>=12&&s.resources.water>=10,reward:{hope:8,seeds:2},memory:"Марфа верит не в спасение, а в заполненную кладовую."},
 {id:"egor_shop",npc:"Егор",title:"Мастерская должна стучать",desc:"Почини мастерскую до 1 уровня и сделай ремонтный набор.",need:s=>s.buildings.workshop>=1&&s.resources.repairKit>=1,consume:{repairKit:1},reward:{fuel:3,battery:1,hope:5},memory:"Егор чинит не железо. Он чинит возможность завтра."},
 {id:"lida_water",npc:"Лида",title:"Чистая вода",desc:"Накопи воду x12 и сделай фильтр.",need:s=>s.resources.water>=12&&s.resources.filter>=1,consume:{filter:1},reward:{medkit:1,hope:9},memory:"Лида говорит: станция начинается там, где больного не бросают."},
 {id:"station_week",npc:"Станция",title:"Первая неделя Здесь",desc:"Переживи 7 дней и восстанови 3 разных здания.",need:s=>s.day>=7&&Object.values(s.buildings).filter(v=>v>0).length>=3,reward:{relic:1,hope:12},memory:"Станция Здесь пережила первую неделю. Значит, она уже спорит с Нигде."}
];
let walkTimer=null,state=migrate(load())||fresh();
function fresh(){let w=pick(weatherList);return{day:1,phaseIndex:0,season:"Оттепель",weather:w[0],weatherText:w[1],stamina:8,hope:42,threat:8,selectedTool:"hand",player:{x:11,y:8,facing:"down",walking:false,step:0},resources:{food:8,water:6,fuel:6,metal:5,wood:4,meds:2,seeds:5,crop:0,ammo:2,repairKit:0,filter:0,medkit:0,tea:0,flare:0,battery:0,relic:0,document:0},buildings:{greenhouse:0,workshop:0,well:0,depot:0,dorm:0,radio:0},plots:gardens.map(()=>({crop:false,stage:0,watered:false})),npcs:npcStart.map(n=>({...n})),completedQuests:[],visited:{},memory:["Станция Здесь — то, что ты строишь. Станция Нигде — то, что зовёт."],flags:{firstRadio:false,visitor:false},log:[]}}
function migrate(s){if(!s)return null;let f=fresh();s={...f,...s,resources:{...f.resources,...(s.resources||{})},buildings:{...f.buildings,...(s.buildings||{})},player:{...f.player,...(s.player||{})},flags:{...f.flags,...(s.flags||{})}};if(!s.completedQuests)s.completedQuests=[];if(!s.visited)s.visited={};if(!s.weather){let w=pick(weatherList);s.weather=w[0];s.weatherText=w[1]}return s}
function load(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))}catch{return null}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function map(){let m=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>x===0||y===0||x===W-1||y===H-1||x===1&&y<6||x===W-2&&y>9||x===2&&y===2||x===19&&y===3||x===20&&y===12?"pine":x>=17&&y>=2&&y<=5?"snow":"grass"));for(let x=1;x<W-1;x++)m[8][x]="rail";for(let y=3;y<15;y++)m[y][11]="dirt";for(let x=4;x<=15;x++)m[11][x]="dirt";for(let x=4;x<=8;x++)m[6][x]="dirt";for(let x=13;x<=18;x++)m[6][x]="dirt";Object.entries({"11,8":"platform","11,13":"home","6,4":"greenhouse","6,12":"workshop","16,4":"well","16,12":"depot","11,2":"radio","13,14":"dorm","4,13":"storage","18,3":"grave","21,8":"gate","19,5":"pond","19,6":"pond"}).forEach(([k,v])=>{let[x,y]=k.split(",").map(Number);m[y][x]=v});gardens.forEach(([x,y])=>m[y][x]="garden");return m}
function phase(){return phases[state.phaseIndex]}
function addLog(t,imp=false){state.log.unshift({text:t,important:imp});state.log=state.log.slice(0,90);toast(t);save()}
function toast(t){let el=$("#toast");if(!el)return;el.textContent=t;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function remember(t){if(!state.memory.includes(t)){state.memory.unshift(t);state.memory=state.memory.slice(0,18);addLog("Память станции: "+t,true)}}
function tile(){return map()[state.player.y][state.player.x]}
function npcAt(x,y){return state.npcs.find(n=>n.x===x&&n.y===y)}
function setTool(tool){if(!tools[tool])return;state.selectedTool=tool;save();renderToolbelt();context()}
function move(dx,dy){let p=state.player,nx=p.x+dx,ny=p.y+dy;if(dx)p.facing=dx>0?"right":"left";if(dy)p.facing=dy>0?"down":"up";if(nx<0||ny<0||nx>=W||ny>=H)return;let t=map()[ny][nx];if(solid.has(t)){addLog(tiles[t][1]+": дальше не пройти.");return render()}p.x=nx;p.y=ny;p.walking=true;p.step=(p.step||0)+1;clearTimeout(walkTimer);save();render();walkTimer=setTimeout(()=>{state.player.walking=false;renderMap()},170)}
function clickTile(x,y){let d=Math.abs(x-state.player.x)+Math.abs(y-state.player.y);if(d===0)return interact();if(d===1)return move(x-state.player.x,y-state.player.y);addLog("Слишком далеко. Подойди ближе.")}
function interact(){let n=npcAt(state.player.x,state.player.y);if(n&&state.selectedTool==="hand")return openDialogue(n);let t=tile();if(state.selectedTool==="hand")return universal(t);if(state.selectedTool==="seed")return t==="garden"?plantGarden():addLog("Семена можно посадить только на грядке.");if(state.selectedTool==="water")return t==="garden"?waterGarden():addLog("Лейка нужна на грядке.");if(state.selectedTool==="hammer")return canRepair(t)?repair(t):addLog("Молотком здесь нечего чинить.");if(state.selectedTool==="crowbar")return crowbar(t);if(state.selectedTool==="radio")return t==="radio"?radio():addLog("Эфир слабый. У башни сигнал будет чище.")}
function universal(t){return({garden:gardenAction,greenhouse:()=>repair("greenhouse"),workshop:()=>repair("workshop"),well,dorm,radio,storage,grave,gate:openExpedition,home,platform,rail,dirt:yard,grass:yard,snow:yard}[t]||yard)()}
function canRepair(t){return["greenhouse","workshop","well","depot","dorm","radio"].includes(t)}
function crowbar(t){if(t==="storage")return storage();if(["grass","dirt","snow"].includes(t))return yard();if(t==="rail")return rail();addLog("Лом скользит по поверхности. Толку мало.")}
function time(txt,cost=1){state.stamina=clamp(state.stamina-cost,0,10);if(txt)addLog(txt);if(state.stamina<=0&&state.phaseIndex<3){addLog("Сил больше нет. День сминается в серый вечер.",true);state.phaseIndex=3}else state.phaseIndex++;if(state.phaseIndex>=4)night();save();render()}
function night(){let eat=Math.max(1,state.npcs.length);state.resources.food-=eat;state.resources.water-=eat;state.threat+=rnd(2,5);if(state.weather==="дождь")state.plots.forEach(p=>{if(p.crop)p.watered=true});state.plots.forEach(p=>{if(p.crop&&p.watered)p.stage=clamp(p.stage+1,0,3);if(p.crop&&!p.watered&&Math.random()<.35)p.crop=false;p.watered=false});if(state.resources.food<0||state.resources.water<0){state.hope-=10;state.resources.food=Math.max(0,state.resources.food);state.resources.water=Math.max(0,state.resources.water);addLog("Ночью не хватило еды или воды. Утром люди говорят тише.",true)}if(state.resources.flare>0&&state.threat>50){state.resources.flare--;state.threat-=14;addLog("Сигнальный факел горит у платформы. Тени держатся дальше.",true)}pick(state.threat>55?[watcher,domovoy,soldiers]:[radioNight,watcher,domovoy,quiet,visitor])();state.day++;if(state.day%9===0)state.season=seasons[(seasons.indexOf(state.season)+1)%seasons.length];let w=pick(weatherList);state.weather=w[0];state.weatherText=w[1];state.phaseIndex=0;state.stamina=8+Math.min(2,state.buildings.dorm);state.hope=clamp(state.hope,0,100);state.threat=clamp(state.threat,0,100);addLog(`Наступает день ${state.day}. Погода: ${state.weather}. ${state.weatherText}`);checkQuestToast();if(state.day===6)addLog("Пятые сутки пережиты. Станция уже не выглядит случайной остановкой.",true)}
function radioNight(){state.hope-=2;state.threat+=state.weather==="радиошторм"?9:4;addLog("Ночью радио включается само: “Здесь — временно. Нигде — навсегда.”",true);remember("Радио не любит, когда станция становится домом.")}
function watcher(){if(state.buildings.workshop||state.buildings.depot){state.threat-=8;addLog("Путевой Смотритель проходит мимо. Отремонтированные стрелки успокаивают его.",true)}else{state.resources.metal=Math.max(0,state.resources.metal-1);state.hope-=6;addLog("Смотритель всю ночь стучит ключом по рельсам. Утром часть металла исчезает.",true)}}
function domovoy(){if(state.buildings.dorm||state.memory.some(m=>m.includes("Домовой"))){state.hope+=2;addLog("Домовой шуршит в общежитии, но сегодня не вредничает.",true)}else{state.hope-=7;state.resources.wood=Math.max(0,state.resources.wood-1);addLog("Комнаты меняются местами. Лида клянётся, что спала в другом вагоне.",true);remember("Домовой боится станций, где у каждого есть своё место.")}}
function soldiers(){if(state.resources.ammo>0)state.resources.ammo--;state.hope-=8;state.threat-=12;addLog("Молчащие Срочники требуют документы на станцию. Марфа ставит печать на пустой бумаге.",true);remember("Приказ иногда сильнее смерти, если произнести его уверенно.")}
function quiet(){state.hope+=4;state.threat-=3;addLog("Ночь проходит тихо. Только тепличный вагон потрескивает от холода.")}
function visitor(){if(!state.flags.visitor&&state.day>2){state.flags.visitor=true;state.hope+=7;state.resources.seeds+=2;addLog("Под утро приходит мальчишка с мешком семян. Он говорит, что уже жил здесь.",true);remember("Некоторые жители приходят раньше своих имён.")}else quiet()}
function gardenAction(){let p=plot();if(!p)return;if(!p.crop)return plantGarden();if(p.stage>=3)return harvestGarden();if(!p.watered)return waterGarden();addLog("Эта грядка уже полита.")}
function plot(){return state.plots[gardenIndex(state.player.x,state.player.y)]}
function plantGarden(){let p=plot();if(!p)return;if(p.crop)return addLog("Здесь уже растёт урожай.");if(state.resources.seeds<=0)return addLog("Семян нет.");state.resources.seeds--;p.crop=true;p.stage=0;p.watered=false;return time("Ты сажаешь семена в мерзловатую землю между шпалами.")}
function waterGarden(){let p=plot();if(!p||!p.crop)return addLog("Сначала нужно посадить семена.");if(p.watered)return addLog("Эта грядка уже полита.");if(state.resources.water<=0)return addLog("Воды нет.");state.resources.water--;p.watered=true;return time("Ты поливаешь грядку.")}
function harvestGarden(){let p=plot();if(!p||!p.crop||p.stage<3)return addLog("Собирать пока нечего.");let a=2+state.buildings.greenhouse;state.resources.crop+=a;state.resources.food+=Math.floor(a/2);p.crop=false;p.stage=0;return time("Урожай собран: +"+a+" овощей.")}
function gardenIndex(x,y){return gardens.findIndex(([gx,gy])=>gx===x&&gy===y)}
function repair(id){let nm={greenhouse:"тепличный вагон",workshop:"мастерскую",depot:"депо",dorm:"общежитие",radio:"сигнальную башню",well:"водокачку"}[id],lvl=state.buildings[id]||0;if(lvl>=2)return addLog("Здесь пока больше нечего чинить.");let mc=2+lvl,wc=1+lvl;if(state.resources.repairKit>0&&(state.resources.metal<mc||state.resources.wood<wc)){state.resources.repairKit--;mc=Math.max(0,mc-2);wc=Math.max(0,wc-1);addLog("Ты используешь ремонтный набор.",true)}if(state.resources.metal<mc||state.resources.wood<wc)return addLog("Для ремонта нужны металл x"+mc+" и дерево x"+wc+".");state.resources.metal-=mc;state.resources.wood-=wc;state.buildings[id]=lvl+1;state.hope+=5;time("Ты ремонтируешь "+nm+". Станция становится чуть меньше похожа на труп.",2)}
function well(){if(state.resources.filter>0){state.resources.filter--;state.resources.water+=4;return time("Фильтр хрипит, но очищает воду: +4.",1)}if(state.buildings.well<2&&state.resources.metal>=2&&state.resources.wood>=1&&Math.random()<.35)return repair("well");let a=2+state.buildings.well*2;state.resources.water+=a;time("Водокачка кашляет ржавчиной, но даёт воду: +"+a+".")}
function dorm(){if(!state.buildings.dorm&&state.resources.metal>=2&&state.resources.wood>=1)return repair("dorm");openDialogue(pick(state.npcs))}
function radio(){if(!state.flags.firstRadio){state.flags.firstRadio=true;remember("Станция Нигде знает настоящее имя обходчика.");return time("Ты включаешь радио. Вместо эфира — дыхание и фраза: “Не строй Здесь слишком крепко.”")}if(state.buildings.radio<2&&state.resources.metal>=2&&Math.random()<.45)return repair("radio");let text=pick([()=>{state.resources.fuel++;return"В эфире называют старый склад ГСМ: +1 топливо."},()=>{state.resources.seeds++;return"Под башней находишь пакет семян."},()=>{state.threat+=6;remember("Чем чаще слушаешь Нигде, тем легче Нигде слышит тебя.");return"Радио зовёт слишком ясно. Станция становится холоднее."}])();time(text)}
function storage(){let f=pick(["metal","wood","food","seeds","document"]),a=f==="food"?2:1;state.resources[f]+=a;state.threat++;time("Ты разбираешь склад и находишь: "+rname(f)+" +"+a+".")}
function grave(){state.hope+=2;remember(pick(["Мёртвые станции ждут, пока кто-нибудь снова назовёт их домом.","Кладбище шпал помнит маршруты лучше карты.","Иногда память — предупреждение из будущего."]));time("Ты поправляешь таблички на кладбище шпал.")}
function home(){if(state.resources.tea>0){state.resources.tea--;state.stamina=clamp(state.stamina+3,0,12);state.hope+=3;return time("Ты пьёшь чай у печки. На минуту кажется, что мир ещё можно пережить.",0)}state.stamina=clamp(state.stamina+2,0,10);state.hope++;time("Ты чинишь печку, кипятишь воду и переписываешь список дел.",0)}
function platform(){state.hope+=3;state.threat=Math.max(0,state.threat-2);time("Ты чистишь платформу и вешаешь табличку: “Станция Здесь”.")}
function rail(){state.threat=Math.max(0,state.threat-1);time("Ты проверяешь путь. Рельсы холодные. Это хороший знак.")}
function yard(){let pool=state.weather==="снег"?["wood","metal","relic"]:["wood","metal","seeds"],f=pick(pool);if(f==="relic"&&Math.random()>.2)f="wood";state.resources[f]++;time(f==="wood"?"Во дворе находишь сухую доску.":f==="metal"?"В снегу торчит кусок годного металла.":"Между шпалами нашёлся пакет семян.")}
function rname(k){return{food:"еда",water:"вода",fuel:"топливо",metal:"металл",wood:"дерево",meds:"лекарства",seeds:"семена",crop:"овощи",ammo:"патроны",repairKit:"ремнабор",filter:"фильтр",medkit:"аптечка",tea:"чай",flare:"факел",battery:"аккумулятор",relic:"реликт",document:"документ"}[k]||k}
function canPay(cost){return Object.entries(cost||{}).every(([k,v])=>(state.resources[k]||0)>=v)}
function pay(cost){Object.entries(cost||{}).forEach(([k,v])=>state.resources[k]-=v)}
function gain(out){Object.entries(out||{}).forEach(([k,v])=>{if(k==="hope")state.hope+=v;else state.resources[k]=(state.resources[k]||0)+v})}
function costText(o){return Object.entries(o||{}).map(([k,v])=>`${rname(k)} x${v}`).join(", ")||"без затрат"}
function outText(o){return Object.entries(o||{}).map(([k,v])=>`${rname(k)} +${v}`).join(", ")||"—"}
function craft(id){let r=recipes.find(x=>x.id===id);if(!r)return;if(!canPay(r.cost))return toast("Не хватает ресурсов: "+costText(r.cost));pay(r.cost);gain(r.out);addLog("Собрано: "+r.name+".",true);render();openCraft()}
function useItem(id){if((state.resources[id]||0)<=0)return;let msg="";if(id==="medkit"){state.resources.medkit--;state.stamina=clamp(state.stamina+4,0,12);state.hope+=3;msg="Аптечка использована: силы и надежда выросли."}else if(id==="tea"){state.resources.tea--;state.stamina=clamp(state.stamina+3,0,12);state.hope+=2;msg="Тёплый чай возвращает руки к жизни."}else if(id==="flare"){state.resources.flare--;state.threat=Math.max(0,state.threat-12);msg="Факел горит ярко. Угроза снижается."}else return toast("Этот предмет пока используется в квестах или крафте.");addLog(msg,true);render();openInventory()}
function openDialogue(n){let body=`<div class="dialogue"><div class="portrait" style="--portrait:${n.color}">${n.portrait}</div><div><h3>${n.name}</h3><p class="muted">${n.role}. ${n.mood}.</p><p>${dialogueLine(n)}</p><p class="muted">Хочет: ${n.want}.</p></div></div>`;showModal(n.name,body,[["Поговорить",()=>{n.heart=clamp(n.heart+1,0,5);state.hope+=3;addLog(`${n.name}: разговор у печки немного укрепляет станцию.`,true);closeModal();render()}],["Показать задания",()=>openQuests()],["Закрыть",closeModal]])}
function dialogueLine(n){let lines={marfa:["Если расписание пустое, это не значит, что поездов больше нет.","Запасы — это тоже молитва. Только честнее.","Станция должна звучать: шаги, чайник, молоток."],egor:["Дрезина не любит страх. Она его глохнет.","Надо чинить мастерскую. Без неё мы просто сидим на рельсах.","Если мотор кашляет ночью — не отвечай ему словами."],lida:["Вода важнее патронов. Патроны не промоют рану.","Не называй людей лишними. Станция слышит.","Мне нужны чистая вода и тишина хотя бы на час."]};return pick(lines[n.id]||["Мы ещё здесь. Значит, не всё потеряно."])}
function openInventory(){let keys=Object.keys(state.resources).filter(k=>state.resources[k]>0);let body=`<div class="inventory-grid">${keys.map(k=>`<div class="inv-slot"><b>${rname(k)}</b><span>${state.resources[k]}</span>${["medkit","tea","flare"].includes(k)?`<button onclick="useItem('${k}')">Использовать</button>`:""}</div>`).join("")}</div>`;showModal("Инвентарь",body,[["Закрыть",closeModal]])}
function openCraft(){let body=`<div class="cards">${recipes.map(r=>`<article class="craft-card"><h3>${r.icon} ${r.name}</h3><p>${r.desc}</p><small>Нужно: ${costText(r.cost)}</small><small>Выход: ${outText(r.out)}</small><button ${canPay(r.cost)?"":"disabled"} onclick="craft('${r.id}')">Собрать</button></article>`).join("")}</div>`;showModal("Крафт",body,[["Закрыть",closeModal]])}
function questStatus(q){if(state.completedQuests.includes(q.id))return"done";return q.need(state)?"ready":"active"}
function openQuests(){let body=`<div class="cards">${quests.map(q=>{let st=questStatus(q);return`<article class="quest-card ${st}"><h3>${st==="done"?"✓ ":""}${q.title}</h3><p><b>${q.npc}</b>: ${q.desc}</p><small>Награда: ${outText(q.reward)}</small>${st==="ready"?`<button onclick="completeQuest('${q.id}')">Завершить</button>`:""}${st==="active"?`<button disabled>В процессе</button>`:""}${st==="done"?`<button disabled>Готово</button>`:""}</article>`}).join("")}</div>`;showModal("Задания жителей",body,[["Закрыть",closeModal]])}
function completeQuest(id){let q=quests.find(x=>x.id===id);if(!q||state.completedQuests.includes(id)||!q.need(state))return;if(q.consume)pay(q.consume);gain(q.reward);state.completedQuests.push(id);remember(q.memory);addLog("Задание выполнено: "+q.title,true);render();openQuests()}
function checkQuestToast(){let ready=quests.find(q=>!state.completedQuests.includes(q.id)&&q.need(state));if(ready)toast("Готово задание: "+ready.title)}
function openExpedition(){let body=`<div class="cards routes">${routes.map(r=>`<article class="route-card"><h3>${r.name}</h3><p>${r.txt}</p><small>Топливо: ${r.fuel} · риск: ${r.risk}</small><button ${state.resources.fuel>=r.fuel?"":"disabled"} onclick="runRoute('${r.id}')">Выехать</button></article>`).join("")}</div>`;showModal("Маршруты дрезины",body,[["Закрыть",closeModal]])}
function runRoute(id){let r=routes.find(x=>x.id===id);if(!r)return;if(state.resources.fuel<r.fuel)return toast("Не хватает топлива.");state.resources.fuel-=r.fuel;state.visited[id]=(state.visited[id]||0)+1;let rew=r.reward();gain(rew);state.threat+=rnd(3,9)+(r.risk==="аномальный"?6:0);remember(r.mem);addLog(r.txt+" Добыча: "+outText(rew)+".",true);showModal(r.name,`<div class="event-card"><p>${r.txt}</p><small>Добыча: ${outText(rew)}. Угроза выросла.</small></div>`,[["Продолжить",closeModal]]);time("",2)}
function openPanel(p){if(p==="inventory")openInventory();if(p==="craft")openCraft();if(p==="quests")openQuests();if(p==="expedition")openExpedition()}
function showModal(title,body,actions=[]){let root=$("#modal-root");root.innerHTML=`<section class="modal-backdrop"><div class="game-modal"><div class="drawer-head"><div><p class="eyebrow">station interface</p><h2>${title}</h2></div><button class="ghost" data-close>Закрыть</button></div><div class="modal-body">${body}</div><div class="modal-actions"></div></div></section>`;root.querySelector("[data-close]").onclick=closeModal;let bar=root.querySelector(".modal-actions");actions.forEach(([label,fn])=>{let b=document.createElement("button");b.textContent=label;b.onclick=fn;bar.appendChild(b)})}
function closeModal(){let root=$("#modal-root");if(root)root.innerHTML=""}
function cam(){let sx=clamp(state.player.x-Math.floor(VW/2),0,W-VW),sy=clamp(state.player.y-Math.floor(VH/2),0,H-VH);return{sx,sy}}
function render(){stats();renderMap();buildings();npcs();memory();log();context();renderToolbelt();renderPreviews()}
function stats(){$("#day").textContent=state.day;$("#phase").textContent=phase();$("#stamina").textContent=state.stamina;$("#hope").textContent=state.hope;$("#threat").textContent=state.threat;let meta=$("#world-meta");if(meta)meta.textContent=`${state.season} · ${state.weather}`;document.body.classList.remove("phase-morning","phase-day","phase-evening","phase-night","weather-fog","weather-snow","weather-rain","weather-radio");document.body.classList.add(["phase-morning","phase-day","phase-evening","phase-night"][state.phaseIndex]||"phase-morning");if(state.weather==="туман")document.body.classList.add("weather-fog");if(state.weather==="снег")document.body.classList.add("weather-snow");if(state.weather==="дождь")document.body.classList.add("weather-rain");if(state.weather==="радиошторм")document.body.classList.add("weather-radio");Object.entries(state.resources).forEach(([k,v])=>{let e=$("#res-"+k);if(e)e.textContent=v})}
function renderMap(){let b=$("#station-map"),m=map(),{sx,sy}=cam();b.style.setProperty("--view-w",VW);b.innerHTML="";for(let y=sy;y<sy+VH;y++)for(let x=sx;x<sx+VW;x++){let t=m[y][x],inf=tiles[t],n=npcAt(x,y),c=document.createElement("button");c.type="button";c.className="station-cell "+inf[2];c.title=n?n.name+" — "+n.role:inf[1];let obj=n?({marfa:"М",egor:"Е",lida:"Л"}[n.id]||"?"):tileObject(t,x,y);c.innerHTML=`<span class="tile-art">${obj}</span><small>${short(t,x,y)}</small>`;if(state.player.x===x&&state.player.y===y){c.classList.add("player");c.innerHTML+=`<span class="hero-sprite ${state.player.facing} ${state.player.walking?"walk":""}"></span>`}c.onclick=()=>clickTile(x,y);b.appendChild(c)}let label=$("#camera-label");if(label)label.innerHTML=`камера: <b>${sx+1}:${sy+1}</b> / мир ${W}×${H}`}
function tileObject(t,x,y){if(t==="garden"){let p=state.plots[gardenIndex(x,y)];if(!p||!p.crop)return"";return p.stage>=3?"✿":"♧"}return tiles[t][0]}
function short(t,x,y){let n=npcAt(x,y);if(n)return n.name;if(t==="garden"){let p=state.plots[gardenIndex(x,y)];if(!p||!p.crop)return"грядка";return p.stage>=3?"урожай":"рост "+p.stage}return{platform:"центр",home:"дом",greenhouse:"теплица",workshop:"цех",well:"вода",depot:"депо",dorm:"жители",radio:"радио",storage:"склад",grave:"память",gate:"выезд",rail:"путь",dirt:"тропа",grass:"трава",snow:"снег",pine:"лес",pond:"лёд"}[t]||""}
function buildings(){let box=$("#buildings"),names={greenhouse:"Тепличный вагон",workshop:"Мастерская",well:"Водокачка",depot:"Депо",dorm:"Общежитие",radio:"Сигнальная башня"};box.innerHTML="";Object.entries(names).forEach(([k,n])=>{let d=document.createElement("div");d.className="upgrade";d.innerHTML=`<span>${n}</span><b>${"▰".repeat(state.buildings[k])}${"▱".repeat(2-state.buildings[k])}</b>`;box.appendChild(d)})}
function npcs(){let box=$("#npcs");box.innerHTML="";state.npcs.forEach(n=>{let d=document.createElement("div");d.className="npc-card";d.innerHTML=`<b>${n.name}</b><span>${n.role}</span><small>${"♥".repeat(n.heart)}${"♡".repeat(5-n.heart)} · ${n.mood}</small>`;box.appendChild(d)})}
function memory(){let box=$("#memory-list");box.innerHTML="";state.memory.forEach(t=>{let d=document.createElement("div");d.className="memory-item";d.textContent=t;box.appendChild(d)})}
function log(){let box=$("#log");box.innerHTML="";state.log.forEach(e=>{let p=document.createElement("p");p.className=e.important?"important":"";p.textContent=e.text;box.appendChild(p)})}
function renderToolbelt(){$$("[data-tool]").forEach(btn=>btn.classList.toggle("active",btn.dataset.tool===state.selectedTool));let el=$("#current-tool"),t=tools[state.selectedTool];if(el&&t)el.textContent=`${t[0]} ${t[1]}: ${t[2]}`}
function renderPreviews(){let inv=$("#inventory-preview");if(inv){let keys=["repairKit","filter","medkit","tea","flare","battery","relic","document"].filter(k=>state.resources[k]>0);inv.innerHTML=(keys.length?keys:["repairKit","filter","medkit"]).slice(0,6).map(k=>`<span>${rname(k)} <b>${state.resources[k]||0}</b></span>`).join("")}let qp=$("#quest-preview");if(qp){let ready=quests.filter(q=>!state.completedQuests.includes(q.id));qp.innerHTML=ready.slice(0,3).map(q=>`<p class="${q.need(state)?"ready":""}">${q.need(state)?"✓ ":"• "}${q.title}</p>`).join("")}}
function context(){let n=npcAt(state.player.x,state.player.y);if(n){$("#place-name").textContent=n.name;$("#place-desc").textContent=n.role+". "+n.mood+". Выбери руку и поговори с ним.";$("#main-action").textContent="Поговорить";return}let t=tile(),tool=state.selectedTool;$("#place-name").textContent=tiles[t][1];$("#place-desc").textContent={garden:"Посади, полей или собери урожай.",greenhouse:"Тепличный вагон повышает урожай после ремонта.",workshop:"Мастерская помогает чинить путь и отпугивать Смотрителя.",well:"Водокачка даёт воду.",depot:"Депо хранит дрезину.",dorm:"Общежитие для жителей.",radio:"Башня ловит Нигде и чужие частоты.",storage:"Склад можно разобрать ради ресурсов.",grave:"Кладбище шпал отдаёт память.",gate:"Выезд на дрезине.",home:"Дом обходчика. Тут можно восстановить силы.",platform:"Сердце станции.",rail:"Пути надо проверять.",grass:"Заросший двор станции.",dirt:"Тропа между вагонами.",snow:"Серый снег у края станции."}[t]||"";$("#main-action").textContent=(tools[tool]?.[0]||"")+" Использовать"}
function openMemory(){$("#memoryDrawer").classList.remove("hidden");memory()}function closeMemory(){$("#memoryDrawer").classList.add("hidden")}function openHelp(){$("#helpDrawer").classList.remove("hidden")}function closeHelp(){$("#helpDrawer").classList.add("hidden")}
function bind(){$("#main-action").onclick=interact;$("#restBtn").onclick=home;$("#memoryBtn").onclick=openMemory;$("#newRunBtn").onclick=()=>{localStorage.removeItem(SAVE_KEY);state=fresh();state.log=[];addLog("Ты возвращаешься на пустую платформу. На табличке мелом написано: “Здесь”.",true);render()};$("#closeMemoryBtn").onclick=closeMemory;$("#helpBtn").onclick=openHelp;$("#closeHelpBtn").onclick=closeHelp;$$("[data-tool]").forEach(btn=>btn.onclick=()=>setTool(btn.dataset.tool));$$("[data-panel]").forEach(btn=>btn.onclick=()=>openPanel(btn.dataset.panel));window.addEventListener("keydown",e=>{let k=e.key.toLowerCase(),mv={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();if(mv[k])move(...mv[k]);if(e.key===" "||e.key==="Enter")interact();if(k>="1"&&k<="6")setTool(toolOrder[Number(k)-1]);if(k==="i")openInventory();if(k==="c")openCraft();if(k==="q")openQuests();if(k==="e")openExpedition();if(k==="escape")closeModal();if(k==="r")home();if(k==="m")openMemory();if(k==="n")$("#newRunBtn").click()})}
window.craft=craft;window.useItem=useItem;window.completeQuest=completeQuest;window.runRoute=runRoute;
if(!state.log.length){addLog("Ты ставишь на платформе табличку: “Станция Здесь”. Вдалеке радио шепчет: “Нигде”.",true);addLog("Открыты системы v7: инвентарь, крафт, задания, маршруты и погода.")}
bind();render();
